### ISSUE TITLE
Convert STRING TO BOOL using CustomPropertyConverter 

### ISSUE THREAD

**Issue by obautista** [LucaMozzo/DbDataReaderMapper#2]
I see the example on converting VARCHAR to ENUM.  How do I convert VARCHAR TO BOOL using CustomPropertyConverter?

**Comment by LucaMozzo** [comment]
Hi @obautista 
apologies for the delay, I didn't see the notification. I know that functionality is not super clear, but 
```
.AddConversion<RecipientSyncObject, string, bool>(x => x.PropertyName, x => Boolean.Parse(x));
```
basically AddConversion<{TypeOfTargetObject}, {TypeOfPropertyAsIsInDatabase}, {TypeYouWantThePropertyToBe}>
